import { createClient, type Session } from '@supabase/supabase-js';
import { Activity, BarChart3, Bell, CheckCircle2, ChevronDown, CircleAlert, ClipboardCheck, Clock3, FileChartColumn, Globe2, LayoutGrid, LogOut, Menu, Plus, RefreshCw, Search, Settings, ShieldCheck, Users, X } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://dfaxmxschvzmlozxjaxf.supabase.co';
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_zNc8TQjoFQ-OI2nKbiNOPA_5ukCoCY6';
const supabase = createClient(supabaseUrl, supabaseKey);
type Property = { id:string; name:string; url:string; canonical_host:string; verification_status:string; tracking_id:string; tracking_last_received_at?:string; uptime_monitors?:any[]; audit_runs?:any[] };
type Bootstrap = { profile:any; accounts:any[]; workspaces:any[]; properties:Property[]; incidents:any[]; notifications:any[] };

async function api<T>(session: Session, path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(path, { ...init, headers: { 'content-type':'application/json', authorization:`Bearer ${session.access_token}`, ...init?.headers } });
  const body: any = await res.json().catch(()=>({})); if (!res.ok) throw new Error(body.error || 'Request failed'); return body as T;
}

export function App(){
  const [session,setSession]=useState<Session|null>(null); const [ready,setReady]=useState(false);
  useEffect(()=>{ supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)}); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe(); },[]);
  if(!ready) return <Splash/>;
  return <Routes><Route path="/auth/*" element={session?<Navigate to="/"/>:<Auth/>}/><Route path="/*" element={session?<Workspace session={session}/>:<Navigate to="/auth/sign-in"/>}/></Routes>;
}

function Auth(){ const nav=useNavigate(); const loc=useLocation(); const mode=loc.pathname.split('/').pop()||'sign-in'; const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage(''); try{
    if(mode==='register'){const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/auth/confirmed`}});if(error)throw error;setMessage('Check your email to confirm your account.');}
    else if(mode==='forgot'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/auth/update-password`});if(error)throw error;setMessage('If an account exists, a reset link has been sent.');}
    else if(mode==='update-password'){const {error}=await supabase.auth.updateUser({password});if(error)throw error;nav('/');}
    else {const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;nav('/');}
  }catch(err:any){setMessage(err.message)}finally{setBusy(false)}}
  const title=mode==='register'?'Create your account':mode==='forgot'?'Reset your password':mode==='update-password'?'Choose a new password':'Welcome back';
  return <main className="auth"><Link to="/" className="auth-logo"><img src="/assets/claritude-logo.svg" alt="Claritude"/></Link><section className="auth-card"><div className="auth-mark"><img src="/assets/claritude-favicon.svg" alt=""/><h1>{title}</h1><p>{mode==='register'?'Start monitoring your first property.':mode==='forgot'?'We will send a secure recovery link.':'Sign in to manage your websites.'}</p></div><form onSubmit={submit}>{mode!=='update-password'&&<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label>}{mode!=='forgot'&&<label>{mode==='update-password'?'New password':'Password'}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} autoComplete={mode==='register'?'new-password':'current-password'} required/></label>}<button className="primary wide" disabled={busy}>{busy?'Please wait…':title}</button>{message&&<div className="notice">{message}</div>}</form><div className="auth-links">{mode==='sign-in'?<><Link to="/auth/forgot">Forgot password?</Link><Link to="/auth/register">Create account</Link></>:<Link to="/auth/sign-in">Back to sign in</Link>}</div></section><footer>Privacy · Terms · Help</footer></main>;
}

function Workspace({session}:{session:Session}){const [data,setData]=useState<Bootstrap|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const load=()=>api<Bootstrap>(session,'/api/bootstrap').then(setData).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
  if(error)return <State title="We could not load your workspace" detail={error} action={<button onClick={load}>Try again</button>}/>;
  if(!data)return <Splash/>;
  if(!data.accounts?.length)return <Onboarding session={session} done={load}/>;
  return <Shell session={session} data={data} reload={load} busy={busy} setBusy={setBusy}/>;
}

function Onboarding({session,done}:{session:Session;done:()=>void}){const [step,setStep]=useState(1);const [accountName,setAccount]=useState('');const [workspaceName,setWorkspace]=useState('');const [propertyName,setProperty]=useState('');const [url,setUrl]=useState('https://');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function finish(){setBusy(true);try{await api(session,'/api/onboarding',{method:'POST',body:JSON.stringify({accountName,workspaceName,propertyName,url:url==='https://'?'':url})});done()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  return <main className="onboarding"><header><img src="/assets/claritude-logo.svg" alt="Claritude"/></header><div className="onboard-shell"><aside><h2>Get started</h2>{['Create account','Create workspace','Add property'].map((x,i)=><div className={`progress ${step===i+1?'active':''} ${step>i+1?'done':''}`} key={x}><span>{step>i+1?'✓':i+1}</span><b>{x}</b></div>)}</aside><section className="onboard-card"><small>Step {step} of 3</small>{step===1&&<><h1>Name your account</h1><p>The account owns access and future billing. Pro is included during early access.</p><label>Account name<input autoFocus value={accountName} onChange={e=>setAccount(e.target.value)} placeholder="Your company"/></label></>}{step===2&&<><h1>Create your workspace</h1><p>A workspace keeps related properties and people together.</p><label>Workspace name<input autoFocus value={workspaceName} onChange={e=>setWorkspace(e.target.value)} placeholder="Main workspace"/></label></>}{step===3&&<><h1>Add your first property</h1><p>Use a public website you control. You can also finish without adding one.</p><label>Property name<input value={propertyName} onChange={e=>setProperty(e.target.value)} placeholder="Company website"/></label><label>Website URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label></>}{error&&<div className="notice danger">{error}</div>}<div className="onboard-actions">{step>1&&<button onClick={()=>setStep(step-1)}>Back</button>}<span/><button className="primary" disabled={busy||step===1&&!accountName||step===2&&!workspaceName} onClick={()=>step<3?setStep(step+1):finish()}>{step<3?'Continue':busy?'Creating…':'Finish setup'}</button></div></section></div></main>;
}

function Shell({session,data,reload,busy,setBusy}:{session:Session;data:Bootstrap;reload:()=>void;busy:boolean;setBusy:(x:boolean)=>void}){const loc=useLocation();const nav=useNavigate();const [mobile,setMobile]=useState(false);const workspace:any=data.workspaces?.[0]?.workspaces;const propertyId=new URLSearchParams(loc.search).get('property')||data.properties?.[0]?.id;const property=data.properties.find(p=>p.id===propertyId);const route=loc.pathname.split('/')[1]||'overview';const section=route||'overview';const items=[['overview','Overview',LayoutGrid],['uptime','Uptime',Activity],['audit','Audit',ClipboardCheck],['analytics','Analytics',BarChart3],['reports','Reports',FileChartColumn],['settings','Property settings',Settings]] as const;
  return <div className="app"><header className="topbar"><button className="workspace-select" onClick={()=>setMobile(!mobile)}><Menu className="mobile-only"/><span className="brand-square">W</span><b>{workspace?.name||'Workspace'}</b><span className="pill">Pro</span><ChevronDown/></button><select aria-label="Select property" value={propertyId||''} onChange={e=>nav(`${loc.pathname}?property=${e.target.value}`)}><option value="">All properties</option>{data.properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><span className="page-name">{items.find(x=>x[0]===section)?.[1]||'Overview'}</span><img src="/assets/claritude-logo.svg" alt="Claritude"/></header><div className="app-body"><aside className={mobile?'open':''}><nav><Link to="/"><Globe2/>All properties</Link>{property&&items.map(([path,label,Icon])=><Link className={section===path?'active':''} to={`/${path}?property=${property.id}`} key={path}><Icon/>{label}</Link>)}</nav><div className="aside-bottom"><Link to="/account"><Users/>Account settings</Link><button onClick={()=>supabase.auth.signOut()}><LogOut/>Sign out</button><div className="user"><span>{(session.user.email||'?')[0].toUpperCase()}</span><div><b>{data.profile?.full_name||'Claritude user'}</b><small>{session.user.email}</small></div></div></div></aside><main onClick={()=>setMobile(false)}>{data.notifications.length>0&&<div className="alertbar"><span/><b>{data.notifications[0].title}</b><p>{data.notifications[0].body}</p><Link to="/account">Review notification</Link></div>}<Routes><Route path="/" element={<Portfolio data={data}/>}/><Route path="/overview" element={<Overview property={property}/>}/><Route path="/uptime" element={<Uptime session={session} property={property} incidents={data.incidents} reload={reload}/>}/><Route path="/audit" element={<Audit session={session} property={property} busy={busy} setBusy={setBusy}/>}/><Route path="/analytics" element={<Analytics session={session} property={property}/>}/><Route path="/reports" element={<Reports session={session} property={property}/>}/><Route path="/settings" element={<PropertySettings property={property}/>}/><Route path="/account" element={<Account data={data}/>}/></Routes></main></div></div>;
}

function Portfolio({data}:{data:Bootstrap}){const [query,setQuery]=useState('');const rows=data.properties.filter(p=>(p.name+p.canonical_host).toLowerCase().includes(query.toLowerCase()));return <Page title="Your properties" actions={<button className="primary"><Plus/>Add property</button>}><Metrics values={[['Properties',data.properties.length,''],['Online',data.properties.filter(p=>p.uptime_monitors?.[0]?.last_status==='online').length,'Latest check'],['Open incidents',data.incidents.filter(i=>!i.resolved_at).length,'Needs attention'],['Early access','Pro','Included']]}/><section className="panel"><div className="toolbar"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search properties"/></div></div><div className="table-scroll"><table><thead><tr><th>Property</th><th>Monitor</th><th>Tracking</th><th>Latest audit</th><th>Verification</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><Link className="property-cell" to={`/overview?property=${p.id}`}><span className="favicon">{p.name[0]}</span><span><b>{p.name}</b><small>{p.canonical_host}</small></span></Link></td><td><Status value={p.uptime_monitors?.[0]?.last_status||'pending'}/></td><td><Status value={p.tracking_last_received_at?'receiving':'not installed'}/></td><td>{p.audit_runs?.[0]?.score??'Not run'}</td><td>{p.verification_status}</td></tr>)}</tbody></table></div>{!rows.length&&<Empty title="No properties match" detail="Clear the search or add a property."/>}</section></Page>}
function Overview({property}:{property?:Property}){if(!property)return <Empty title="Add your first property" detail="Properties appear here after setup."/>;const monitor=property.uptime_monitors?.[0];const audit=property.audit_runs?.[0];return <Page title={property.name} eyebrow={property.canonical_host}><Metrics values={[['Website status',monitor?.last_status||'Pending',''],['Response time',monitor?.last_response_ms?`${monitor.last_response_ms} ms`:'—','HTTP response'],['Audit score',audit?.score??'Not run',audit?.coverage?`${audit.coverage}% coverage`:''],['Tracking',property.tracking_last_received_at?'Receiving data':'Not installed','']]}/><div className="two-col"><section className="panel"><PanelTitle title="Setup"/><Checklist items={[[property.verification_status==='verified','Property verified'],[!!monitor,'Uptime monitoring enabled'],[!!property.tracking_last_received_at,'Analytics receiving data'],[!!audit,'First audit completed']]}/></section><section className="panel"><PanelTitle title="Activity"/><Empty title="Real activity appears here" detail="Audits, incidents and configuration changes are recorded as they happen."/></section></div></Page>}
function Uptime({session,property,incidents,reload}:{session:Session;property?:Property;incidents:any[];reload:()=>void}){const monitor=property?.uptime_monitors?.[0];async function check(){if(!monitor)return;await api(session,`/api/monitors/${monitor.id}/check`,{method:'POST'});setTimeout(reload,1500)}return <Page title="Uptime" actions={<button className="primary" disabled={!monitor} onClick={check}><RefreshCw/>Check now</button>}><Metrics values={[['Current status',monitor?.last_status||'Not configured',''],['Latest response',monitor?.last_response_ms?`${monitor.last_response_ms} ms`:'—','HTTP response'],['Check interval',monitor?`${monitor.interval_minutes} min`:'—',''],['Open incidents',incidents.filter(i=>i.property_id===property?.id&&!i.resolved_at).length,'']]}/><Tabs labels={['Overview','Incidents','Maintenance','Alerts','Monitor settings']}/><section className="panel"><PanelTitle title="Incident history"/><SimpleTable headers={['Opened','Cause','Status','Resolved']} rows={incidents.filter(i=>i.property_id===property?.id).map(i=>[fmtDate(i.opened_at),i.cause,i.resolved_at?'Recovered':'Open',i.resolved_at?fmtDate(i.resolved_at):'—'])}/></section></Page>}
function Audit({session,property,busy,setBusy}:{session:Session;property?:Property;busy:boolean;setBusy:(v:boolean)=>void}){const [runs,setRuns]=useState<any[]>([]);const [error,setError]=useState('');const load=()=>property&&api<any[]>(session,`/api/properties/${property.id}/audits`).then(setRuns).catch(e=>setError(e.message));useEffect(()=>{load()},[property?.id]);async function start(){if(!property)return;setBusy(true);try{await api(session,'/api/audits',{method:'POST',body:JSON.stringify({propertyId:property.id})});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}const latest=runs[0];return <Page title="Website audit" actions={<button className="primary" onClick={start} disabled={!property||busy}><RefreshCw/>{busy?'Queuing…':'Run audit'}</button>}><Metrics values={[['Overall score',latest?.score??'—',latest?.status||'Not run'],['Coverage',latest?.coverage!=null?`${latest.coverage}%`:'—','Mapped catalogue'],['Checks',latest?.audit_results?.length||0,'Evidence-backed'],['Last run',latest?fmtDate(latest.created_at):'Never','']]}/><Tabs labels={['Overview','Findings','Checks','History','Compare']}/>{error&&<div className="notice danger">{error}</div>}<section className="panel"><PanelTitle title="Audit history"/><SimpleTable headers={['Started','Status','Score','Coverage','Duration']} rows={runs.map(r=>[fmtDate(r.created_at),r.status,r.score??'—',r.coverage!=null?`${r.coverage}%`:'—',r.duration_ms?`${r.duration_ms} ms`:'—'])}/></section></Page>}
function Analytics({session,property}:{session:Session;property?:Property}){const [data,setData]=useState<any>(null);useEffect(()=>{if(property)api(session,`/api/properties/${property.id}/analytics?days=30`).then(setData).catch(()=>setData(null))},[property?.id]);const snippet=property?`<script defer src="${location.origin}/tracker.js" data-property="${property.tracking_id}"></script>`:'';return <Page title="Analytics"><Metrics values={[['Pageviews',data?.pageviews||0,'Last 30 days'],['Events',data?.events||0,'Cookieless'],['Pages',data?.pages?.length||0,'Observed'],['Last received',property?.tracking_last_received_at?fmtDate(property.tracking_last_received_at):'Never','']]}/><Tabs labels={['Overview','Pages','Sources','Events','Audience','Engagement','Performance']}/>{!property?.tracking_last_received_at?<section className="panel install"><ShieldCheck/><div><h2>Install privacy-conscious analytics</h2><p>No cookies, persistent visitor IDs, form contents or sensitive query strings are collected.</p><pre><code>{snippet}</code></pre><button onClick={()=>navigator.clipboard.writeText(snippet)}>Copy installation code</button></div></section>:<section className="panel"><PanelTitle title="Traffic"/><Chart/></section>}</Page>}
function Reports({session,property}:{session:Session;property?:Property}){const [report,setReport]=useState<any>();async function preview(){if(property)setReport(await api(session,`/api/properties/${property.id}/report`))}return <Page title="Reports" actions={<button className="primary" onClick={preview} disabled={!property}>Preview report</button>}><Tabs labels={['Quick reports','Saved reports','Schedules','Branding']}/><div className="cards"><article className="report-card"><FileChartColumn/><h2>Monthly website health</h2><p>Uptime, analytics and audit coverage for the selected property and period.</p><button onClick={preview}>Preview</button></article><article className="report-card"><Clock3/><h2>Scheduled reports</h2><p>Create saved schedules after a delivery email is configured.</p><button disabled>Configure</button></article></div>{report&&<section className="panel"><PanelTitle title={`${report.property.name} · ${report.period}`}/><pre className="report-json">{JSON.stringify(report,null,2)}</pre></section>}</Page>}
function PropertySettings({property}:{property?:Property}){if(!property)return <Empty title="Select a property" detail="Property settings require a selected property."/>;return <Page title="Property settings"><Tabs labels={['General','Tracking','Uptime','Sharing','Advanced']}/><section className="panel form-grid"><label>Property name<input defaultValue={property.name}/></label><label>Website URL<input defaultValue={property.url}/></label><label>Verification status<input value={property.verification_status} readOnly/></label><label>Tracking ID<input value={property.tracking_id} readOnly/></label><div className="form-actions"><button>Cancel</button><button className="primary">Save changes</button></div></section></Page>}
function Account({data}:{data:Bootstrap}){return <Page title="Account settings"><Tabs labels={['Profile','Workspace','Billing & plan','Users','Notification preferences','Activity logs','Security','Data & privacy']}/><section className="panel"><div className="plan"><div><small>Current access</small><h2>Pro early access</h2><p>Pro access is included during early access.</p></div><ShieldCheck/></div></section><section className="panel form-grid"><label>Full name<input defaultValue={data.profile?.full_name||''}/></label><label>Timezone<select defaultValue={data.profile?.timezone||'Europe/London'}><option>Europe/London</option><option>UTC</option></select></label><div className="form-actions"><button className="primary">Save profile</button></div></section></Page>}

function Page({title,eyebrow,actions,children}:{title:string;eyebrow?:string;actions?:any;children:any}){return <div className="content"><div className="title-row"><div>{eyebrow&&<small>{eyebrow}</small>}<h1>{title}</h1></div><span/>{actions}</div>{children}</div>}
function Metrics({values}:{values:(string|number)[][]}){return <div className="metrics">{values.map((v,i)=><div className="metric" key={i}><small>{v[0]}</small><b>{v[1]}</b><span>{v[2]}</span></div>)}</div>}
function Tabs({labels}:{labels:string[]}){return <div className="tabs">{labels.map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div>}
function PanelTitle({title}:{title:string}){return <div className="panel-title"><h2>{title}</h2><button aria-label={`${title} options`}>•••</button></div>}
function Status({value}:{value:string}){return <span className={`status ${value.replace(' ','-')}`}><i/>{value}</span>}
function Checklist({items}:{items:[boolean,string][]}){return <div className="checklist">{items.map(([ok,label])=><div key={label}>{ok?<CheckCircle2/>:<CircleAlert/>}<b>{label}</b><span>{ok?'Complete':'Needs attention'}</span></div>)}</div>}
function SimpleTable({headers,rows}:{headers:string[];rows:any[][]}){return <div className="table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty title="No data yet" detail="Results will appear after the first completed run."/>}</div>}
function Chart(){return <div className="chart" aria-label="Traffic chart"><div className="chart-grid"/>{[42,64,51,78,61,84,72,96,81,102,91,118,108,126,111,137,128,145,132,156,143,168,151,176].map((h,i)=><span key={i} style={{height:`${h/1.9}px`}}/>)}</div>}
function Empty({title,detail}:{title:string;detail:string}){return <div className="empty"><Globe2/><b>{title}</b><p>{detail}</p></div>}
function State({title,detail,action}:{title:string;detail:string;action?:any}){return <main className="state"><CircleAlert/><h1>{title}</h1><p>{detail}</p>{action}</main>}
function Splash(){return <main className="splash"><img src="/assets/claritude-favicon.svg" alt=""/><span/></main>}
function fmtDate(x:string){return new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}
