-- Stage 3 rationalised user-facing audit catalogue.
-- Preserves all technical result rows and stores only configuration/mappings plus a compact per-run group snapshot.

begin;

create table public.audit_user_facing_groups (
  id text primary key,
  name text not null,
  category text not null check (category in ('SEO','Accessibility','Performance','Security','Technical','AI & Crawler Readiness')),
  subcategory text not null,
  presentation_role text not null,
  outcome_policy text not null,
  failure_severity text not null,
  weight numeric(8,3) not null default 0 check (weight >= 0),
  authoritative_reference text,
  lifecycle public.check_lifecycle not null default 'active',
  enabled_by_default boolean not null default true,
  configuration_version integer not null default 1 check (configuration_version > 0),
  sort_order integer not null check (sort_order > 0),
  changed_by uuid references auth.users on delete set null,
  changed_at timestamptz not null default now()
);

create table public.audit_user_facing_group_checks (
  group_id text not null references public.audit_user_facing_groups(id) on delete cascade,
  check_id text not null references public.audit_check_definitions(id) on delete restrict,
  presentation_action text not null,
  lifecycle public.check_lifecycle not null default 'active',
  enabled_by_default boolean not null default true,
  sort_order integer not null check (sort_order > 0),
  changed_by uuid references auth.users on delete set null,
  changed_at timestamptz not null default now(),
  primary key (group_id, check_id),
  unique (check_id)
);

create index audit_user_facing_groups_availability_idx on public.audit_user_facing_groups(lifecycle, enabled_by_default, sort_order);
create index audit_user_facing_group_checks_availability_idx on public.audit_user_facing_group_checks(lifecycle, enabled_by_default, group_id, sort_order);

create table public.audit_catalogue_package_availability (
  target_kind text not null check (target_kind in ('technical_check','user_facing_group')),
  target_id text not null,
  entitlement text not null,
  enabled boolean not null,
  changed_by uuid references auth.users on delete set null,
  changed_at timestamptz not null default now(),
  primary key (target_kind, target_id, entitlement)
);

create table public.audit_catalogue_account_availability (
  target_kind text not null check (target_kind in ('technical_check','user_facing_group')),
  target_id text not null,
  account_id uuid not null references public.accounts(id) on delete cascade,
  enabled boolean not null,
  changed_by uuid references auth.users on delete set null,
  changed_at timestamptz not null default now(),
  primary key (target_kind, target_id, account_id)
);

create index audit_catalogue_package_entitlement_idx on public.audit_catalogue_package_availability(entitlement, target_kind, target_id);
create index audit_catalogue_account_account_idx on public.audit_catalogue_account_availability(account_id, target_kind, target_id);

alter table public.audit_user_facing_groups enable row level security;
alter table public.audit_user_facing_group_checks enable row level security;
alter table public.audit_catalogue_package_availability enable row level security;
alter table public.audit_catalogue_account_availability enable row level security;
revoke all on public.audit_user_facing_groups from anon, authenticated;
revoke all on public.audit_user_facing_group_checks from anon, authenticated;

revoke all on public.audit_catalogue_package_availability from anon, authenticated;
revoke all on public.audit_catalogue_account_availability from anon, authenticated;

alter table public.audit_runs add column user_facing_snapshot jsonb not null default '[]'::jsonb;

insert into public.audit_user_facing_groups (id,name,category,subcategory,presentation_role,outcome_policy,failure_severity,weight,authoritative_reference,lifecycle,enabled_by_default,configuration_version,sort_order) values
  ('audit-group.ai-and-crawler-readiness.ai-content-accessibility', 'AI content accessibility', 'AI & Crawler Readiness', 'AI Content Accessibility', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.openai.com/api/docs/bots', 'active', true, 1, 1),
  ('audit-group.ai-and-crawler-readiness.ai-content-structure', 'AI content structure', 'AI & Crawler Readiness', 'AI Content Accessibility', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.openai.com/api/docs/bots', 'active', true, 1, 2),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'Content attribution and identity', 'AI & Crawler Readiness', 'Content & Attribution', 'Advisory / contextual', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://developers.openai.com/api/docs/bots', 'active', true, 1, 3),
  ('audit-group.ai-and-crawler-readiness.ai-snippet-restrictions', 'AI snippet restrictions', 'AI & Crawler Readiness', 'Crawler Permissions', 'Contextual / policy-dependent', 'Contextual: report policy/state; do not Fail without declared intent', 'Advisory / contextual', 0, 'https://developers.openai.com/api/docs/bots', 'active', true, 1, 4),
  ('audit-group.ai-and-crawler-readiness.markdown-alternatives', 'Markdown alternatives', 'AI & Crawler Readiness', 'Optional AI Resources', 'Advisory / optional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://llmstxt.org/', 'active', true, 1, 5),
  ('audit-group.ai-and-crawler-readiness.llms-full-txt', 'llms-full.txt', 'AI & Crawler Readiness', 'Optional AI Resources', 'Advisory / optional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://llmstxt.org/', 'active', true, 1, 6),
  ('audit-group.ai-and-crawler-readiness.llms-txt', 'llms.txt', 'AI & Crawler Readiness', 'Optional AI Resources', 'Advisory / optional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://llmstxt.org/', 'active', true, 1, 7),
  ('audit-group.accessibility.aria-validity', 'ARIA validity', 'Accessibility', 'ARIA', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/ARIA/apg/', 'active', true, 1, 8),
  ('audit-group.accessibility.button-accessible-names', 'Button accessible names', 'Accessibility', 'Forms & Controls', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html', 'active', true, 1, 9),
  ('audit-group.accessibility.form-control-labels', 'Form control labels', 'Accessibility', 'Forms & Controls', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/tutorials/forms/labels/', 'active', true, 1, 10),
  ('audit-group.accessibility.navigation-control-names', 'Navigation control names', 'Accessibility', 'Forms & Controls', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 11),
  ('audit-group.accessibility.alt-text-repeats-image-filenames', 'Alt text repeats image filenames', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 12),
  ('audit-group.accessibility.autoplaying-media', 'Autoplaying media', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 13),
  ('audit-group.accessibility.iframe-titles', 'Iframe titles', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 14),
  ('audit-group.accessibility.image-delivery', 'Image delivery', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 15),
  ('audit-group.accessibility.image-loading', 'Image loading', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/Lazy_loading', 'active', true, 1, 16),
  ('audit-group.accessibility.image-resources-fail-to-load', 'Image resources fail to load', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 17),
  ('audit-group.accessibility.image-sizing-and-dimensions', 'Image sizing and dimensions', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 18),
  ('audit-group.accessibility.images-contain-alt-attributes', 'Images contain alt attributes', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 19),
  ('audit-group.accessibility.images-marked-decorative-remain-focusable', 'Images marked decorative remain focusable', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 20),
  ('audit-group.accessibility.responsive-images', 'Responsive images', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 21),
  ('audit-group.accessibility.svg-accessible-names', 'SVG accessible names', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 22),
  ('audit-group.accessibility.video-captions', 'Video captions', 'Accessibility', 'Images & Media', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 23),
  ('audit-group.accessibility.keyboard-and-focus', 'Keyboard and focus', 'Accessibility', 'Keyboard & Focus', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 24),
  ('audit-group.accessibility.empty-alt-attributes', 'Empty alt attributes', 'Accessibility', 'Page Structure', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 25),
  ('audit-group.accessibility.meta-refresh', 'Meta refresh', 'Accessibility', 'Page Structure', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 26),
  ('audit-group.accessibility.heading-visibility', 'Heading visibility', 'Accessibility', 'Responsive Accessibility', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/tutorials/page-structure/headings/', 'active', true, 1, 27),
  ('audit-group.accessibility.mobile-text-sizing', 'Mobile text sizing', 'Accessibility', 'Responsive Accessibility', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 28),
  ('audit-group.accessibility.responsive-content-consistency', 'Responsive content consistency', 'Accessibility', 'Responsive Accessibility', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 29),
  ('audit-group.accessibility.responsive-layout-overflow', 'Responsive layout overflow', 'Accessibility', 'Responsive Accessibility', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 30),
  ('audit-group.accessibility.viewport-configuration', 'Viewport configuration', 'Accessibility', 'Responsive Accessibility', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html', 'active', true, 1, 31),
  ('audit-group.accessibility.accessible-lists', 'Accessible lists', 'Accessibility', 'Tables & Lists', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/quickref/', 'active', true, 1, 32),
  ('audit-group.accessibility.accessible-tables', 'Accessible tables', 'Accessibility', 'Tables & Lists', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/tutorials/tables/', 'active', true, 1, 33),
  ('audit-group.accessibility.colour-contrast', 'Colour contrast', 'Accessibility', 'Visual & Interaction', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html', 'active', true, 1, 34),
  ('audit-group.accessibility.touch-targets', 'Touch targets', 'Accessibility', 'Visual & Interaction', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html', 'active', true, 1, 35),
  ('audit-group.performance.cumulative-layout-shift', 'Cumulative Layout Shift', 'Performance', 'Core Web Vitals & Rendering', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/articles/cls', 'active', true, 1, 36),
  ('audit-group.performance.first-contentful-paint', 'First Contentful Paint', 'Performance', 'Core Web Vitals & Rendering', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/articles/fcp', 'active', true, 1, 37),
  ('audit-group.performance.largest-contentful-paint', 'Largest Contentful Paint', 'Performance', 'Core Web Vitals & Rendering', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/articles/lcp', 'active', true, 1, 38),
  ('audit-group.performance.total-blocking-time', 'Total Blocking Time', 'Performance', 'Core Web Vitals & Rendering', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/articles/tbt', 'active', true, 1, 39),
  ('audit-group.performance.font-loading', 'Font loading', 'Performance', 'Delivery & Caching', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 40),
  ('audit-group.performance.resource-preloads', 'Resource preloads', 'Performance', 'Delivery & Caching', 'Advisory / conditional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://web.dev/performance/', 'active', true, 1, 41),
  ('audit-group.performance.static-resource-caching', 'Static resource caching', 'Performance', 'Delivery & Caching', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching', 'active', true, 1, 42),
  ('audit-group.performance.text-compression', 'Text compression', 'Performance', 'Delivery & Caching', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/articles/uses-text-compression', 'active', true, 1, 43),
  ('audit-group.performance.long-main-thread-tasks', 'Long main-thread tasks', 'Performance', 'Execution & Rendering', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 44),
  ('audit-group.performance.render-blocking-resources', 'Render-blocking resources', 'Performance', 'Execution & Rendering', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 45),
  ('audit-group.performance.css-transfer-size', 'CSS transfer size', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 46),
  ('audit-group.performance.font-transfer-size', 'Font transfer size', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 47),
  ('audit-group.performance.image-transfer-size', 'Image transfer size', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 48),
  ('audit-group.performance.javascript-runtime-errors', 'JavaScript runtime errors', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 49),
  ('audit-group.performance.javascript-transfer-size', 'JavaScript transfer size', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 50),
  ('audit-group.performance.page-transfer-size', 'Page transfer size', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 51),
  ('audit-group.performance.resource-request-count', 'Resource request count', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 52),
  ('audit-group.performance.third-party-requests', 'Third-party requests', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 53),
  ('audit-group.performance.unused-css', 'Unused CSS', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 54),
  ('audit-group.performance.unused-javascript', 'Unused JavaScript', 'Performance', 'Page Weight & Requests', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 55),
  ('audit-group.performance.server-response-time', 'Server response time', 'Performance', 'Performance Metrics', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/articles/ttfb', 'active', true, 1, 56),
  ('audit-group.performance.failed-network-requests', 'Failed network requests', 'Performance', 'Reliability', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 57),
  ('audit-group.performance.repeated-resource-downloads', 'Repeated resource downloads', 'Performance', 'Reliability', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 58),
  ('audit-group.performance.lcp-resource-optimisation', 'LCP resource optimisation', 'Performance', 'Rendering Diagnostics', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 59),
  ('audit-group.performance.layout-shift-contributors', 'Layout shift contributors', 'Performance', 'Rendering Diagnostics', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://web.dev/performance/', 'active', true, 1, 60),
  ('audit-group.seo.h1-headings', 'H1 headings', 'SEO', 'Content & Structure', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/tutorials/page-structure/headings/', 'active', true, 1, 61),
  ('audit-group.seo.heading-structure', 'Heading structure', 'SEO', 'Content & Structure', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/tutorials/page-structure/headings/', 'active', true, 1, 62),
  ('audit-group.seo.main-content-availability', 'Main content availability', 'SEO', 'Content & Structure', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 63),
  ('audit-group.seo.main-content-landmark', 'Main content landmark', 'SEO', 'Content & Structure', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 64),
  ('audit-group.seo.semantic-content-structures', 'Semantic content structures', 'SEO', 'Content & Structure', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 65),
  ('audit-group.seo.crawler-permissions', 'Crawler permissions', 'SEO', 'Crawling & Indexing', 'Contextual / policy-dependent', 'Contextual: report policy/state; do not Fail without declared intent', 'Advisory / contextual', 0, 'https://developers.openai.com/api/docs/bots', 'active', true, 1, 66),
  ('audit-group.seo.indexing-directives', 'Indexing directives', 'SEO', 'Crawling & Indexing', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag', 'active', true, 1, 67),
  ('audit-group.seo.page-redirects', 'Page redirects', 'SEO', 'Crawling & Indexing', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 68),
  ('audit-group.seo.redirecting-links', 'Redirecting links', 'SEO', 'Crawling & Indexing', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 69),
  ('audit-group.seo.robots-txt', 'Robots.txt', 'SEO', 'Crawling & Indexing', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/crawling-indexing/robots/intro', 'active', true, 1, 70),
  ('audit-group.seo.xml-sitemap', 'XML sitemap', 'SEO', 'Crawling & Indexing', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview', 'active', true, 1, 71),
  ('audit-group.seo.contact-link-formats', 'Contact link formats', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 72),
  ('audit-group.seo.download-links', 'Download links', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 73),
  ('audit-group.seo.https-page-links-to-http-destinations', 'HTTPS page links to HTTP destinations', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 74),
  ('audit-group.seo.javascript-link-destinations', 'JavaScript link destinations', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 75),
  ('audit-group.seo.link-destination-health', 'Link destination health', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 76),
  ('audit-group.seo.link-inventory', 'Link inventory', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 77),
  ('audit-group.seo.link-relationship-attributes', 'Link relationship attributes', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 78),
  ('audit-group.seo.link-text-and-accessible-names', 'Link text and accessible names', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html', 'active', true, 1, 79),
  ('audit-group.seo.links-have-non-empty-destinations', 'Links have non-empty destinations', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 80),
  ('audit-group.seo.navigation-landmarks-have-distinguishable-accessible-names', 'Navigation landmarks have distinguishable accessible names', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 81),
  ('audit-group.seo.on-page-fragment-links-point-to-existing-elements', 'On-page fragment links point to existing elements', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 82),
  ('audit-group.seo.placeholder-link-destinations', 'Placeholder link destinations', 'SEO', 'Links & Navigation', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 83),
  ('audit-group.seo.canonical-url', 'Canonical URL', 'SEO', 'Page Metadata', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls', 'active', true, 1, 84),
  ('audit-group.seo.html-language', 'HTML language', 'SEO', 'Page Metadata', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 85),
  ('audit-group.seo.meta-description', 'Meta description', 'SEO', 'Page Metadata', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/appearance/snippet', 'active', true, 1, 86),
  ('audit-group.seo.page-response', 'Page response', 'SEO', 'Page Metadata', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Critical', 3, 'https://developers.google.com/search/docs', 'active', true, 1, 87),
  ('audit-group.seo.page-title', 'Page title', 'SEO', 'Page Metadata', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/appearance/title-link', 'active', true, 1, 88),
  ('audit-group.seo.apple-touch-icon', 'Apple touch icon', 'SEO', 'Social & Sharing', 'Advisory / optional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://developers.google.com/search/docs', 'active', true, 1, 89),
  ('audit-group.seo.conflicting-duplicate-social-metadata', 'Conflicting duplicate social metadata', 'SEO', 'Social & Sharing', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs', 'active', true, 1, 90),
  ('audit-group.seo.favicon', 'Favicon', 'SEO', 'Social & Sharing', 'Advisory / optional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://developers.google.com/search/docs', 'active', true, 1, 91),
  ('audit-group.seo.open-graph-metadata', 'Open Graph metadata', 'SEO', 'Social & Sharing', 'Advisory / optional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://ogp.me/', 'active', true, 1, 92),
  ('audit-group.seo.web-app-manifest', 'Web app manifest', 'SEO', 'Social & Sharing', 'Advisory / optional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://developers.google.com/search/docs', 'active', true, 1, 93),
  ('audit-group.seo.x-card-metadata', 'X Card metadata', 'SEO', 'Social & Sharing', 'Advisory / optional', 'Advisory when absent/suboptimal; Pass only when positively verified; N/A where irrelevant', 'Advisory', 0, 'https://developer.x.com/en/docs/x-for-websites/cards/overview/abouts-cards', 'active', true, 1, 94),
  ('audit-group.seo.article-structured-data', 'Article structured data', 'SEO', 'Structured Data', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data', 'active', true, 1, 95),
  ('audit-group.seo.breadcrumb-structured-data', 'Breadcrumb structured data', 'SEO', 'Structured Data', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data', 'active', true, 1, 96),
  ('audit-group.seo.organisation-structured-data', 'Organisation structured data', 'SEO', 'Structured Data', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data', 'active', true, 1, 97),
  ('audit-group.seo.product-structured-data', 'Product structured data', 'SEO', 'Structured Data', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data', 'active', true, 1, 98),
  ('audit-group.seo.structured-data-validity', 'Structured data validity', 'SEO', 'Structured Data', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data', 'active', true, 1, 99),
  ('audit-group.security.content-security-policy', 'Content Security Policy', 'Security', 'Content Security Policy', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html', 'active', true, 1, 100),
  ('audit-group.security.cookie-security', 'Cookie security', 'Security', 'Cookie Security', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie', 'active', true, 1, 101),
  ('audit-group.security.secure-forms-and-credentials', 'Secure forms and credentials', 'Security', 'Forms & Credentials', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html', 'active', true, 1, 102),
  ('audit-group.security.https-availability', 'HTTPS availability', 'Security', 'HTTPS & Transport', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Critical', 3, 'https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html', 'active', true, 1, 103),
  ('audit-group.security.mixed-content', 'Mixed content', 'Security', 'HTTPS & Transport', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content', 'active', true, 1, 104),
  ('audit-group.security.frame-embedding-protection', 'Frame embedding protection', 'Security', 'Security Headers', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html', 'active', true, 1, 105),
  ('audit-group.security.http-strict-transport-security', 'HTTP Strict Transport Security', 'Security', 'Security Headers', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html', 'active', true, 1, 106),
  ('audit-group.security.mime-sniffing-protection', 'MIME sniffing protection', 'Security', 'Security Headers', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html', 'active', true, 1, 107),
  ('audit-group.security.permissions-policy', 'Permissions Policy', 'Security', 'Security Headers', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html', 'active', true, 1, 108),
  ('audit-group.security.referrer-policy', 'Referrer Policy', 'Security', 'Security Headers', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Security', 2, 'https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html', 'active', true, 1, 109),
  ('audit-group.technical.apex-and-www-redirect-behaviour', 'Apex and www redirect behaviour', 'Technical', 'DNS & Domain', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP', 'active', true, 1, 110),
  ('audit-group.technical.caa-configuration', 'CAA configuration', 'Technical', 'DNS & Domain', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.rfc-editor.org/rfc/rfc8659', 'active', true, 1, 111),
  ('audit-group.technical.dmarc-configuration', 'DMARC configuration', 'Technical', 'DNS & Domain', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.rfc-editor.org/rfc/rfc7489', 'active', true, 1, 112),
  ('audit-group.technical.dns-configuration', 'DNS configuration', 'Technical', 'DNS & Domain', 'Mixed: checks + diagnostics', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.cloudflare.com/learning/dns/what-is-dns/', 'active', true, 1, 113),
  ('audit-group.technical.mail-exchange-records', 'Mail exchange records', 'Technical', 'DNS & Domain', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP', 'active', true, 1, 114),
  ('audit-group.technical.spf-configuration', 'SPF configuration', 'Technical', 'DNS & Domain', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://www.rfc-editor.org/rfc/rfc7208', 'active', true, 1, 115),
  ('audit-group.technical.cdn-reverse-proxy', 'CDN / reverse proxy', 'Technical', 'Server & HTTP', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP', 'active', true, 1, 116),
  ('audit-group.technical.cache-status', 'Cache status', 'Technical', 'Server & HTTP', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP', 'active', true, 1, 117),
  ('audit-group.technical.response-format', 'Response format', 'Technical', 'Server & HTTP', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP', 'active', true, 1, 118),
  ('audit-group.technical.server-timing', 'Server timing', 'Technical', 'Server & HTTP', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP', 'active', true, 1, 119),
  ('audit-group.technical.technology-disclosure', 'Technology disclosure', 'Technical', 'Server & HTTP', 'Scored check', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP', 'active', true, 1, 120),
  ('audit-group.technical.http-caching-metadata', 'HTTP caching metadata', 'Technical', 'Technical Diagnostics', 'Mixed: checks + diagnostics', 'Passed / Failed / Not applicable / Unable to test', 'Warning', 1, 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching', 'active', true, 1, 121);

do $$
begin
  if (select count(*) from public.audit_check_definitions) >= 306 then
    insert into public.audit_user_facing_group_checks (group_id,check_id,presentation_action,lifecycle,enabled_by_default,sort_order) values
  ('audit-group.ai-and-crawler-readiness.ai-content-accessibility', 'ai.content.source_extractable', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.ai-and-crawler-readiness.ai-content-accessibility', 'ai_readiness.content.and.attribution.main.content.extractable.after.javascript.rendering', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.ai-and-crawler-readiness.ai-content-accessibility', 'ai_readiness.content.and.attribution.login.requirement.encountered.by.the.audit.runner', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.ai-and-crawler-readiness.ai-content-accessibility', 'ai_readiness.content.and.attribution.bot.challenge.encountered.by.the.audit.runner', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.ai-and-crawler-readiness.ai-content-accessibility', 'ai_readiness.content.and.attribution.main.content.includes.machine.readable.text', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.ai-and-crawler-readiness.ai-content-structure', 'ai_readiness.content.and.attribution.main.content.organised.under.semantic.headings', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.ai-and-crawler-readiness.ai-content-structure', 'ai_readiness.content.and.attribution.lists.available.in.machine.readable.html', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.ai-and-crawler-readiness.ai-content-structure', 'ai_readiness.content.and.attribution.tables.available.in.machine.readable.html', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'ai_readiness.content.and.attribution.author.attribution.declared.in.structured.data', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'ai_readiness.content.and.attribution.publisher.attribution.declared.in.structured.data', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'ai_readiness.content.and.attribution.publication.date.declared.in.structured.data', 'Merge into advisory group', 'active', true, 3),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'ai_readiness.content.and.attribution.modification.date.declared.in.structured.data', 'Merge into advisory group', 'active', true, 4),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'ai_readiness.content.and.attribution.external.source.links.present.in.the.main.content', 'Merge into advisory group', 'active', true, 5),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'ai_readiness.content.and.attribution.machine.readable.organisation.identity.present', 'Merge into advisory group', 'active', true, 6),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'ai_readiness.content.and.attribution.machine.readable.author.identity.present', 'Merge into advisory group', 'active', true, 7),
  ('audit-group.ai-and-crawler-readiness.content-attribution-and-identity', 'ai_readiness.content.and.attribution.entity.sameas.references.use.valid.url.formats', 'Merge into advisory group', 'active', true, 8),
  ('audit-group.ai-and-crawler-readiness.ai-snippet-restrictions', 'ai_readiness.crawler.permissions.nosnippet.restrictions.detected', 'Merge into contextual group', 'active', true, 1),
  ('audit-group.ai-and-crawler-readiness.ai-snippet-restrictions', 'ai_readiness.crawler.permissions.max.snippet.restrictions.detected', 'Merge into contextual group', 'active', true, 2),
  ('audit-group.ai-and-crawler-readiness.ai-snippet-restrictions', 'ai_readiness.crawler.permissions.data.nosnippet.sections.detected', 'Merge into contextual group', 'active', true, 3),
  ('audit-group.ai-and-crawler-readiness.markdown-alternatives', 'ai_readiness.optional.resources.linked.markdown.alternative.for.the.selected.page.detected', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.ai-and-crawler-readiness.markdown-alternatives', 'ai_readiness.optional.resources.declared.markdown.alternative.reachable', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.ai-and-crawler-readiness.markdown-alternatives', 'ai_readiness.optional.resources.declared.markdown.alternative.contains.readable.content', 'Merge into advisory group', 'active', true, 3),
  ('audit-group.ai-and-crawler-readiness.llms-full-txt', 'ai_readiness.optional.resources.llms.full.txt.file.reachable', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.ai-and-crawler-readiness.llms-full-txt', 'ai_readiness.optional.resources.llms.full.txt.returned.as.readable.text', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.ai-and-crawler-readiness.llms-txt', 'ai_readiness.optional.resources.llms.txt.file.reachable', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.ai-and-crawler-readiness.llms-txt', 'ai_readiness.optional.resources.llms.txt.returned.as.readable.text', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.ai-and-crawler-readiness.llms-txt', 'ai_readiness.optional.resources.llms.txt.title.detected', 'Merge into advisory group', 'active', true, 3),
  ('audit-group.ai-and-crawler-readiness.llms-txt', 'ai_readiness.optional.resources.llms.txt.summary.detected', 'Merge into advisory group', 'active', true, 4),
  ('audit-group.ai-and-crawler-readiness.llms-txt', 'ai_readiness.optional.resources.llms.txt.markdown.links.parse.correctly', 'Merge into advisory group', 'active', true, 5),
  ('audit-group.ai-and-crawler-readiness.llms-txt', 'ai_readiness.optional.resources.llms.txt.links.checked.within.the.request.limit', 'Merge into advisory group', 'active', true, 6),
  ('audit-group.ai-and-crawler-readiness.llms-txt', 'ai_readiness.optional.resources.selected.page.referenced.in.checked.llms.txt.links', 'Merge into advisory group', 'active', true, 7),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.required.aria.attributes.present', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.aria.attribute.names.valid', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.aria.attribute.values.valid', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.aria.roles.valid', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.aria.attributes.permitted.for.their.roles', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.required.aria.parent.roles.present', 'Merge into user-facing group', 'active', true, 6),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.required.aria.child.roles.present', 'Merge into user-facing group', 'active', true, 7),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.aria.references.point.to.existing.elements', 'Merge into user-facing group', 'active', true, 8),
  ('audit-group.accessibility.aria-validity', 'accessibility.accessibility.duplicate.ids.used.by.accessibility.references.detected', 'Merge into user-facing group', 'active', true, 9),
  ('audit-group.accessibility.button-accessible-names', 'accessibility.accessibility.buttons.have.accessible.names', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.button-accessible-names', 'accessibility.accessibility.image.buttons.have.accessible.names', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.form-control-labels', 'accessibility.accessibility.form.inputs.have.accessible.labels', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.form-control-labels', 'accessibility.accessibility.select.controls.have.accessible.labels', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.form-control-labels', 'accessibility.accessibility.textareas.have.accessible.labels', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.accessibility.form-control-labels', 'accessibility.accessibility.form.labels.reference.existing.controls', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.accessibility.form-control-labels', 'accessibility.accessibility.multiple.labels.for.the.same.control.detected', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.accessibility.navigation-control-names', 'accessibility.mobile.and.responsive.layout.primary.navigation.controls.have.accessible.names', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.alt-text-repeats-image-filenames', 'accessibility.images.and.media.alt.text.repeats.image.filenames', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.autoplaying-media', 'accessibility.images.and.media.autoplaying.media.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.iframe-titles', 'accessibility.images.and.media.iframes.have.accessible.titles', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.image-delivery', 'accessibility.images.and.media.image.formats.recorded', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.image-delivery', 'accessibility.images.and.media.image.transfer.sizes.measured', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.image-loading', 'accessibility.images.and.media.below.the.fold.image.loading.attributes.inspected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.image-loading', 'accessibility.images.and.media.largest.contentful.paint.image.uses.lazy.loading', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.image-resources-fail-to-load', 'accessibility.images.and.media.image.resources.fail.to.load', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.image-sizing-and-dimensions', 'accessibility.images.and.media.image.intrinsic.dimensions.recorded', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.image-sizing-and-dimensions', 'accessibility.images.and.media.image.display.dimensions.recorded', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.image-sizing-and-dimensions', 'accessibility.images.and.media.oversized.images.relative.to.display.dimensions.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.accessibility.image-sizing-and-dimensions', 'accessibility.images.and.media.image.width.and.height.attributes.present', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.accessibility.image-sizing-and-dimensions', 'accessibility.images.and.media.image.aspect.ratio.distortion.detected', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.accessibility.images-contain-alt-attributes', 'accessibility.images.and.media.images.contain.alt.attributes', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.images-marked-decorative-remain-focusable', 'accessibility.images.and.media.images.marked.decorative.remain.focusable', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.responsive-images', 'accessibility.images.and.media.responsive.srcset.declarations.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.responsive-images', 'accessibility.images.and.media.invalid.srcset.descriptors.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.svg-accessible-names', 'accessibility.accessibility.svg.elements.requiring.accessible.names.have.names', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.video-captions', 'accessibility.images.and.media.videos.contain.caption.track.declarations', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.video-captions', 'accessibility.images.and.media.caption.track.resources.reachable', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.keyboard-and-focus', 'accessibility.accessibility.focusable.elements.inside.aria.hidden.content.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.keyboard-and-focus', 'accessibility.accessibility.nested.interactive.controls.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.keyboard-and-focus', 'accessibility.accessibility.positive.tabindex.values.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.accessibility.keyboard-and-focus', 'accessibility.accessibility.scrollable.regions.keyboard.focusable', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.accessibility.empty-alt-attributes', 'accessibility.images.and.media.empty.alt.attributes.identified', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.meta-refresh', 'accessibility.accessibility.meta.refresh.redirects.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.heading-visibility', 'accessibility.mobile.and.responsive.layout.main.heading.visible.at.tested.widths', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.mobile-text-sizing', 'accessibility.mobile.and.responsive.layout.text.sizes.measured.at.tested.mobile.widths', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.responsive-content-consistency', 'accessibility.mobile.and.responsive.layout.desktop.and.mobile.content.differences.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.responsive-layout-overflow', 'accessibility.mobile.and.responsive.layout.horizontal.page.overflow.detected.at.tested.widths', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.responsive-layout-overflow', 'accessibility.mobile.and.responsive.layout.images.exceed.their.containing.elements', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.responsive-layout-overflow', 'accessibility.mobile.and.responsive.layout.tables.overflow.their.containing.elements', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.accessibility.responsive-layout-overflow', 'accessibility.mobile.and.responsive.layout.fixed.elements.geometrically.overlap.main.content.at.tested.widths', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.accessibility.viewport-configuration', 'accessibility.accessibility.viewport.settings.restrict.zoom', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.viewport-configuration', 'accessibility.mobile.viewport', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.viewport-configuration', 'accessibility.mobile.and.responsive.layout.multiple.viewport.declarations.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.accessibility.viewport-configuration', 'accessibility.mobile.and.responsive.layout.viewport.width.configured.for.device.width', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.accessibility.viewport-configuration', 'accessibility.mobile.and.responsive.layout.elements.extend.beyond.tested.viewports', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.accessibility.accessible-lists', 'accessibility.accessibility.definition.lists.have.valid.structure', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.accessible-lists', 'accessibility.accessibility.lists.contain.valid.list.items', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.accessible-tables', 'accessibility.accessibility.table.headers.associated.with.data.cells', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.accessibility.accessible-tables', 'accessibility.accessibility.table.header.cells.contain.text', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.accessibility.colour-contrast', 'accessibility.accessibility.text.contrast.measured.where.calculable', 'Keep as standalone', 'active', true, 1),
  ('audit-group.accessibility.touch-targets', 'accessibility.accessibility.touch.target.size.and.spacing.checked', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.cumulative-layout-shift', 'performance.performance.cumulative.layout.shift.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.first-contentful-paint', 'performance.performance.first.contentful.paint.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.largest-contentful-paint', 'performance.performance.largest.contentful.paint.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.total-blocking-time', 'performance.performance.total.blocking.time.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.font-loading', 'performance.performance.font.display.declarations.inspected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.resource-preloads', 'performance.performance.resource.preload.declarations.inspected', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.performance.resource-preloads', 'performance.performance.preloaded.resources.unused.during.the.test.detected', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.performance.static-resource-caching', 'performance.performance.static.resource.cache.directives.inspected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.text-compression', 'performance.performance.text.compression.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.long-main-thread-tasks', 'performance.performance.long.main.thread.tasks.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.render-blocking-resources', 'performance.performance.render.blocking.resources.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.css-transfer-size', 'performance.performance.css.transfer.size.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.font-transfer-size', 'performance.performance.font.transfer.size.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.image-transfer-size', 'performance.performance.image.transfer.size.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.javascript-runtime-errors', 'performance.performance.browser.console.errors.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.performance.javascript-runtime-errors', 'performance.performance.uncaught.javascript.exceptions.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.performance.javascript-transfer-size', 'performance.performance.javascript.transfer.size.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.page-transfer-size', 'performance.performance.total.transferred.page.size.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.resource-request-count', 'performance.performance.total.resource.request.count.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.third-party-requests', 'performance.performance.third.party.request.count.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.unused-css', 'performance.performance.unused.css.estimated', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.unused-javascript', 'performance.performance.unused.javascript.estimated', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.server-response-time', 'performance.performance.document.response.time.measured', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.failed-network-requests', 'performance.performance.failed.network.requests.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.repeated-resource-downloads', 'performance.performance.repeated.downloads.of.the.same.resource.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.performance.lcp-resource-optimisation', 'performance.performance.largest.contentful.paint.element.identified', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.performance.lcp-resource-optimisation', 'performance.performance.largest.contentful.paint.resource.discovery.delay.measured', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.performance.layout-shift-contributors', 'performance.performance.layout.shift.contributors.identified', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.h1-headings', 'seo.content.h1.present', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.h1-headings', 'seo.content.structure.and.headings.empty.h1.headings.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.h1-headings', 'seo.content.h1.multiple', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.heading-structure', 'seo.content.structure.and.headings.empty.h2.to.h6.headings.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.heading-structure', 'seo.content.structure.and.headings.skipped.heading.levels.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.heading-structure', 'seo.content.structure.and.headings.repeated.heading.text.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.main-content-availability', 'seo.content.structure.and.headings.main.content.contains.extractable.text', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.main-content-availability', 'seo.content.structure.and.headings.main.content.word.count.measured', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.main-content-availability', 'seo.content.structure.and.headings.text.present.in.original.html', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.main-content-availability', 'seo.content.structure.and.headings.content.added.only.after.javascript.rendering.detected', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.main-content-availability', 'seo.content.structure.and.headings.original.html.and.rendered.text.differences.detected', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.seo.main-content-landmark', 'seo.content.structure.and.headings.main.content.landmark.present', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.main-content-landmark', 'seo.content.structure.and.headings.multiple.main.content.landmarks.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.semantic-content-structures', 'seo.content.structure.and.headings.lists.use.semantic.list.elements', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.semantic-content-structures', 'seo.content.structure.and.headings.data.tables.contain.header.cells', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.crawler-permissions', 'seo.crawling.and.indexing.selected.page.allowed.by.googlebot.robots.rules', 'Merge into contextual group', 'active', true, 1),
  ('audit-group.seo.crawler-permissions', 'seo.crawling.and.indexing.selected.page.allowed.by.bingbot.robots.rules', 'Merge into contextual group', 'active', true, 2),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.selected.page.allowed.by.oai.searchbot.robots.rules', 'Merge into contextual group', 'active', true, 3),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.selected.page.allowed.by.gptbot.robots.rules', 'Merge into contextual group', 'active', true, 4),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.selected.page.allowed.by.claude.searchbot.robots.rules', 'Merge into contextual group', 'active', true, 5),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.selected.page.allowed.by.claudebot.robots.rules', 'Merge into contextual group', 'active', true, 6),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.explicit.chatgpt.user.robots.rules.detected', 'Merge into contextual group', 'active', true, 7),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.explicit.claude.user.robots.rules.detected', 'Merge into contextual group', 'active', true, 8),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.ai.search.and.training.crawler.permissions.differ', 'Merge into contextual group', 'active', true, 9),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.ai.crawler.rules.inherited.from.wildcard.directives.identified', 'Merge into contextual group', 'active', true, 10),
  ('audit-group.seo.crawler-permissions', 'ai_readiness.crawler.permissions.googlebot.robots.access.for.the.selected.page.checked', 'Merge into contextual group', 'active', true, 11),
  ('audit-group.seo.indexing-directives', 'seo.crawling.and.indexing.meta.robots.directives.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.indexing-directives', 'seo.crawling.and.indexing.x.robots.tag.directives.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.indexing-directives', 'seo.crawling.and.indexing.conflicting.indexing.directives.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.indexing-directives', 'seo.crawling.and.indexing.noindex.directive.detected', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.indexing-directives', 'seo.crawling.and.indexing.nofollow.directive.detected', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.seo.page-redirects', 'seo.crawling.and.indexing.redirect.chain.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.page-redirects', 'seo.crawling.and.indexing.redirect.loop.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.page-redirects', 'seo.links.and.navigation.checked.links.containing.redirect.loops.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.redirecting-links', 'seo.links.and.navigation.redirecting.internal.links.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.redirecting-links', 'seo.links.and.navigation.redirecting.external.links.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.robots-txt', 'seo.crawling.and.indexing.robots.txt.file.reachable', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.robots-txt', 'seo.crawling.and.indexing.robots.txt.contains.readable.text', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.robots-txt', 'seo.crawling.and.indexing.robots.txt.parsing.errors.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.robots-txt', 'seo.crawling.and.indexing.sitemap.url.declared.in.robots.txt', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.xml-sitemap', 'seo.crawling.and.indexing.conventional.sitemap.locations.checked', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.xml-sitemap', 'seo.crawling.and.indexing.referenced.xml.sitemap.reachable', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.xml-sitemap', 'seo.crawling.and.indexing.referenced.sitemap.xml.valid', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.xml-sitemap', 'seo.crawling.and.indexing.selected.page.found.in.checked.sitemap.files', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.xml-sitemap', 'seo.crawling.and.indexing.sitemap.lastmod.date.formats.valid', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.seo.contact-link-formats', 'seo.links.and.navigation.telephone.link.formats.checked', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.contact-link-formats', 'seo.links.and.navigation.email.link.formats.checked', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.download-links', 'seo.links.and.navigation.download.links.identified', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.https-page-links-to-http-destinations', 'seo.links.and.navigation.https.page.links.to.http.destinations', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.javascript-link-destinations', 'seo.links.and.navigation.javascript.link.destinations.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.returning.http.404.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.returning.http.410.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.returning.server.errors.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.failing.dns.resolution.detected', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.failing.https.connections.detected', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.timing.out.detected', 'Merge into user-facing group', 'active', true, 6),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.blocked.by.access.restrictions.detected', 'Merge into user-facing group', 'active', true, 7),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.encountering.rate.limits.detected', 'Merge into user-facing group', 'active', true, 8),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.exceeding.the.redirect.limit.detected', 'Merge into user-facing group', 'active', true, 9),
  ('audit-group.seo.link-destination-health', 'seo.links.and.navigation.checked.links.redirecting.to.broken.destinations.detected', 'Merge into user-facing group', 'active', true, 10),
  ('audit-group.seo.link-inventory', 'seo.links.and.navigation.internal.links.identified', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.link-inventory', 'seo.links.and.navigation.external.links.identified', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.link-inventory', 'seo.links.and.navigation.checked.and.unchecked.link.totals.recorded', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.link-relationship-attributes', 'seo.links.and.navigation.sponsored.link.attributes.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.link-relationship-attributes', 'seo.links.and.navigation.user.generated.content.link.attributes.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.link-text-and-accessible-names', 'seo.links.and.navigation.links.have.accessible.names', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.link-text-and-accessible-names', 'seo.links.and.navigation.empty.anchor.text.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.links-have-non-empty-destinations', 'seo.links.and.navigation.links.have.non.empty.destinations', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.navigation-landmarks-have-distinguishable-accessible-names', 'seo.links.and.navigation.navigation.landmarks.have.distinguishable.accessible.names', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.on-page-fragment-links-point-to-existing-elements', 'seo.links.and.navigation.on.page.fragment.links.point.to.existing.elements', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.placeholder-link-destinations', 'seo.links.and.navigation.placeholder.link.destinations.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.canonical-url', 'seo.page.metadata.canonical.url.declared', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.canonical-url', 'seo.page.metadata.multiple.canonical.urls.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.canonical-url', 'seo.page.metadata.canonical.url.format.valid', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.canonical-url', 'seo.page.metadata.canonical.target.reachable', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.canonical-url', 'seo.page.metadata.canonical.target.redirects', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.seo.canonical-url', 'seo.page.metadata.canonical.target.contains.a.noindex.directive', 'Merge into user-facing group', 'active', true, 6),
  ('audit-group.seo.canonical-url', 'seo.page.metadata.canonical.points.to.a.different.page', 'Merge into user-facing group', 'active', true, 7),
  ('audit-group.seo.html-language', 'seo.page.metadata.html.language.declared', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.html-language', 'seo.page.metadata.html.language.code.valid', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.meta-description', 'seo.metadata.description.present', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.meta-description', 'seo.metadata.description.not_empty', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.meta-description', 'seo.page.metadata.multiple.meta.descriptions.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.meta-description', 'seo.page.metadata.meta.description.length.measured', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.page-response', 'seo.crawling.http_status', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.page-response', 'seo.crawling.html_content', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.page-title', 'seo.metadata.title.present', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.page-title', 'seo.metadata.title.not_empty', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.page-title', 'seo.page.metadata.multiple.page.titles.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.page-title', 'seo.metadata.title.length', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.page-title', 'accessibility.document.title', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.seo.apple-touch-icon', 'seo.social.sharing.and.site.identity.apple.touch.icon.declared', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.seo.apple-touch-icon', 'seo.social.sharing.and.site.identity.declared.apple.touch.icon.reachable', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.seo.conflicting-duplicate-social-metadata', 'seo.social.sharing.and.site.identity.conflicting.duplicate.social.metadata.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.seo.favicon', 'seo.social.sharing.and.site.identity.favicon.declared', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.seo.favicon', 'seo.social.sharing.and.site.identity.declared.favicon.reachable', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.open.graph.title.present', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.open.graph.description.present', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.open.graph.url.present', 'Merge into advisory group', 'active', true, 3),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.open.graph.type.present', 'Merge into advisory group', 'active', true, 4),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.open.graph.image.declared', 'Merge into advisory group', 'active', true, 5),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.open.graph.image.reachable', 'Merge into advisory group', 'active', true, 6),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.open.graph.image.dimensions.measured', 'Merge into advisory group', 'active', true, 7),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.open.graph.url.agrees.with.the.canonical.url', 'Merge into advisory group', 'active', true, 8),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.x.twitter.title.or.open.graph.fallback.available', 'Merge into advisory group', 'active', true, 9),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.x.twitter.description.or.open.graph.fallback.available', 'Merge into advisory group', 'active', true, 10),
  ('audit-group.seo.open-graph-metadata', 'seo.social.sharing.and.site.identity.x.twitter.image.or.open.graph.fallback.available', 'Merge into advisory group', 'active', true, 11),
  ('audit-group.seo.web-app-manifest', 'seo.social.sharing.and.site.identity.web.app.manifest.linked', 'Merge into advisory group', 'active', true, 1),
  ('audit-group.seo.web-app-manifest', 'seo.social.sharing.and.site.identity.linked.web.app.manifest.reachable', 'Merge into advisory group', 'active', true, 2),
  ('audit-group.seo.web-app-manifest', 'seo.social.sharing.and.site.identity.web.app.manifest.contains.valid.json', 'Merge into advisory group', 'active', true, 3),
  ('audit-group.seo.x-card-metadata', 'seo.social.sharing.and.site.identity.x.twitter.card.type.declared', 'Keep as advisory', 'active', true, 1),
  ('audit-group.seo.article-structured-data', 'seo.structured.data.article.headline.declared', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.article-structured-data', 'seo.structured.data.article.author.declared', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.article-structured-data', 'seo.structured.data.article.publication.date.declared', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.article-structured-data', 'seo.structured.data.article.modification.date.declared', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.breadcrumb-structured-data', 'seo.structured.data.breadcrumb.items.have.names.and.positions', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.breadcrumb-structured-data', 'seo.structured.data.breadcrumb.positions.form.a.consistent.sequence', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.organisation-structured-data', 'seo.structured.data.organisation.name.declared', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.organisation-structured-data', 'seo.structured.data.organisation.website.declared', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.product-structured-data', 'seo.structured.data.declared.product.price.formats.valid', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.product-structured-data', 'seo.structured.data.declared.product.currency.codes.valid', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.json.ld.blocks.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.json.ld.syntax.valid', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.schema.org.types.identified', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.structured.data.context.declared', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.structured.data.url.identifiers.use.valid.formats', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.structured.data.url.properties.use.valid.formats', 'Merge into user-facing group', 'active', true, 6),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.local.entity.references.resolve.within.the.document', 'Merge into user-facing group', 'active', true, 7),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.duplicate.entity.identifiers.contain.conflicting.values', 'Merge into user-facing group', 'active', true, 8),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.structured.data.dates.use.valid.formats', 'Merge into user-facing group', 'active', true, 9),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.checked.structured.data.image.urls.reachable', 'Merge into user-facing group', 'active', true, 10),
  ('audit-group.seo.structured-data-validity', 'seo.structured.data.structured.data.page.url.matches.the.selected.url', 'Merge into user-facing group', 'active', true, 11),
  ('audit-group.security.content-security-policy', 'security.headers.csp', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.security.content-security-policy', 'security.security.and.browser.protections.content.security.policy.is.report.only', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.security.content-security-policy', 'security.security.and.browser.protections.content.security.policy.contains.unsafe.inline.allowances', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.security.content-security-policy', 'security.security.and.browser.protections.content.security.policy.contains.unsafe.eval.allowances', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.security.content-security-policy', 'security.security.and.browser.protections.browser.reported.security.policy.violations.detected', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.security.cookie-security', 'security.security.and.browser.protections.observed.cookies.have.secure.attributes', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.security.cookie-security', 'security.security.and.browser.protections.observed.cookies.have.httponly.attributes', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.security.cookie-security', 'security.security.and.browser.protections.observed.cookies.have.samesite.attributes', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.security.cookie-security', 'infrastructure.server.and.http.information.response.cookie.attributes.recorded', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.security.secure-forms-and-credentials', 'security.security.and.browser.protections.insecure.form.submission.destinations.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.security.secure-forms-and-credentials', 'security.security.and.browser.protections.password.fields.appear.on.an.http.page', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.security.https-availability', 'security.https.selected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.security.https-availability', 'security.security.and.browser.protections.http.version.redirects.to.https', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.security.https-availability', 'security.security.and.browser.protections.https.connection.succeeds', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.security.mixed-content', 'security.security.and.browser.protections.active.mixed.content.requests.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.security.mixed-content', 'security.security.and.browser.protections.http.image.and.media.references.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.security.frame-embedding-protection', 'security.security.and.browser.protections.frame.embedding.protection.declared', 'Keep as standalone', 'active', true, 1),
  ('audit-group.security.http-strict-transport-security', 'security.headers.hsts', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.security.http-strict-transport-security', 'security.security.and.browser.protections.strict.transport.security.directives.parse.correctly', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.security.mime-sniffing-protection', 'security.security.and.browser.protections.x.content.type.options.header.present', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.security.mime-sniffing-protection', 'security.security.and.browser.protections.x.content.type.options.set.to.nosniff', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.security.permissions-policy', 'security.security.and.browser.protections.permissions.policy.header.present', 'Keep as standalone', 'active', true, 1),
  ('audit-group.security.referrer-policy', 'security.security.and.browser.protections.referrer.policy.declared', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.security.referrer-policy', 'security.security.and.browser.protections.referrer.policy.value.recognised', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.technical.apex-and-www-redirect-behaviour', 'infrastructure.dns.and.domain.configuration.apex.and.www.http.redirect.behaviour.compared', 'Keep as standalone', 'active', true, 1),
  ('audit-group.technical.caa-configuration', 'infrastructure.dns.and.domain.configuration.caa.certificate.authority.restrictions.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.technical.dmarc-configuration', 'infrastructure.dns.and.domain.configuration.dmarc.record.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.technical.dmarc-configuration', 'infrastructure.dns.and.domain.configuration.dmarc.policy.recorded', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.selected.hostname.resolves.successfully', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.ipv4.addresses.recorded', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.ipv6.addresses.recorded', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.returned.cname.records.recorded', 'Merge into user-facing group', 'active', true, 4),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.returned.dns.record.ttls.recorded', 'Merge into user-facing group', 'active', true, 5),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.domain.nameservers.recorded', 'Merge into user-facing group', 'active', true, 6),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.domain.soa.record.recorded', 'Merge into user-facing group', 'active', true, 7),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.dns.resolver.errors.detected', 'Merge into user-facing group', 'active', true, 8),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.non.existent.hostname.response.detected', 'Merge into user-facing group', 'active', true, 9),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.dnssec.validation.status.reported.by.the.resolver', 'Merge into user-facing group', 'active', true, 10),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.apex.domain.resolution.checked', 'Merge into user-facing group', 'active', true, 11),
  ('audit-group.technical.dns-configuration', 'infrastructure.dns.and.domain.configuration.www.hostname.resolution.checked', 'Merge into user-facing group', 'active', true, 12),
  ('audit-group.technical.mail-exchange-records', 'infrastructure.dns.and.domain.configuration.mail.exchange.records.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.technical.spf-configuration', 'infrastructure.dns.and.domain.configuration.spf.record.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.technical.spf-configuration', 'infrastructure.dns.and.domain.configuration.multiple.spf.records.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.technical.cdn-reverse-proxy', 'infrastructure.server.and.http.information.cdn.or.reverse.proxy.header.indicators.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.technical.cache-status', 'infrastructure.server.and.http.information.cache.hit.or.miss.headers.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.technical.response-format', 'infrastructure.http.content_type', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.technical.response-format', 'infrastructure.server.and.http.information.response.character.encoding.declared', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.technical.server-timing', 'infrastructure.server.and.http.information.server.timing.metrics.detected', 'Keep as standalone', 'active', true, 1),
  ('audit-group.technical.technology-disclosure', 'infrastructure.server.and.http.information.server.software.header.detected', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.technical.technology-disclosure', 'infrastructure.server.and.http.information.technology.disclosure.headers.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.technical.http-caching-metadata', 'infrastructure.server.and.http.information.cache.control.directives.recorded', 'Merge into user-facing group', 'active', true, 1),
  ('audit-group.technical.http-caching-metadata', 'infrastructure.server.and.http.information.etag.header.detected', 'Merge into user-facing group', 'active', true, 2),
  ('audit-group.technical.http-caching-metadata', 'infrastructure.server.and.http.information.last.modified.header.detected', 'Merge into user-facing group', 'active', true, 3),
  ('audit-group.technical.http-caching-metadata', 'infrastructure.server.and.http.information.vary.header.recorded', 'Merge into user-facing group', 'active', true, 4);
  end if;
end $$;

comment on table public.audit_user_facing_groups is 'Stable Stage 3 user-facing audit group definitions. Availability is configurable for future SuperAdmin controls.';
comment on table public.audit_user_facing_group_checks is 'Mapping from retained technical checks to rationalised user-facing groups. Disabled mappings are excluded from execution and scoring.';
comment on table public.audit_catalogue_package_availability is 'Optional package-level availability overrides. Absence preserves the target default.';
comment on table public.audit_catalogue_account_availability is 'Optional account-level availability overrides applied after package defaults.';
comment on column public.audit_runs.user_facing_snapshot is 'Compact effective user-facing grouping snapshot for this run; evidence remains in technical audit_results rows.';

insert into private.app_migrations(version, name, checksum)
values ('20261004133552', 'stage3_user_facing_audit_groups', 'self')
on conflict (version) do nothing;

commit;
