-- Claritude V2 Stage 1. Apply through Supabase migrations after review.
create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create type public.member_role as enum ('owner','member','viewer');
create type public.audit_status as enum ('queued','running','completed','partial','failed');
create type public.check_outcome as enum ('pass','warning','fail','informational','not_applicable','unable_to_test');
create type public.check_lifecycle as enum ('draft','active','disabled','deprecated','retired');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, timezone text not null default 'Europe/London', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.accounts (id uuid primary key default gen_random_uuid(), name text not null check(char_length(name) between 1 and 100), entitlement text not null default 'pro_early_access', entitlement_started_at timestamptz not null default now(), entitlement_ends_at timestamptz, created_at timestamptz not null default now());
create table public.account_memberships (account_id uuid not null references public.accounts on delete cascade, user_id uuid not null references auth.users on delete cascade, role public.member_role not null default 'member', created_at timestamptz not null default now(), primary key(account_id,user_id));
create table public.workspaces (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.accounts on delete cascade, name text not null check(char_length(name) between 1 and 100), created_at timestamptz not null default now());
create table public.workspace_memberships (workspace_id uuid not null references public.workspaces on delete cascade, user_id uuid not null references auth.users on delete cascade, role public.member_role not null default 'member', created_at timestamptz not null default now(), primary key(workspace_id,user_id));
create table public.properties (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, name text not null check(char_length(name) between 1 and 100), url text not null check(url ~ '^https?://'), canonical_host text not null, verification_status text not null default 'pending' check(verification_status in ('pending','verified','failed')), verified_at timestamptz, tracking_id text not null unique, tracking_enabled boolean not null default true, tracking_last_received_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.uptime_monitors (id uuid primary key default gen_random_uuid(), property_id uuid not null unique references public.properties on delete cascade, enabled boolean not null default true, interval_minutes int not null default 5 check(interval_minutes in (5,10,15,30,60)), timeout_ms int not null default 10000 check(timeout_ms between 1000 and 30000), expected_status_min int not null default 200 check(expected_status_min between 100 and 599), expected_status_max int not null default 399 check(expected_status_max between 100 and 599), failure_threshold int not null default 2 check(failure_threshold between 1 and 5), consecutive_failures int not null default 0, last_status text not null default 'pending' check(last_status in ('pending','online','offline','paused')), last_response_ms int, last_checked_at timestamptz, next_check_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.uptime_checks (id bigint generated always as identity primary key, monitor_id uuid not null references public.uptime_monitors on delete cascade, checked_at timestamptz not null, success boolean not null, status_code int, response_ms int, error_code text, constraint response_nonnegative check(response_ms is null or response_ms>=0));
create table public.maintenance_windows (id uuid primary key default gen_random_uuid(), monitor_id uuid not null references public.uptime_monitors on delete cascade, starts_at timestamptz not null, ends_at timestamptz not null check(ends_at>starts_at), reason text, created_by uuid references auth.users, created_at timestamptz not null default now());
create table public.incidents (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties on delete cascade, monitor_id uuid references public.uptime_monitors on delete set null, opened_at timestamptz not null, resolved_at timestamptz, cause text, created_at timestamptz not null default now());
create table public.alert_recipients (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties on delete cascade, email text not null, enabled boolean not null default true, created_at timestamptz not null default now(), unique(property_id,email));

create table public.audit_check_definitions (id text primary key, title text not null, description text not null, primary_category text not null check(primary_category in ('seo','performance','accessibility','security','infrastructure','ai_readiness')), subcategory text not null, tags text[] not null default '{}', source_reference text not null, scope text not null, applicability text not null, execution_method text not null, measurements text[] not null default '{}', timeout_class text not null, thresholds jsonb not null default '{}', severity text not null, recommendation text not null, weight numeric(8,3) not null default 1 check(weight>=0), informational boolean not null default false, logic_version text not null, configuration_version int not null default 1, lifecycle public.check_lifecycle not null default 'draft', replacement_check_id text references public.audit_check_definitions, disabled_reason text, changed_by uuid references auth.users, changed_at timestamptz not null default now());
create table public.audit_check_history (id bigint generated always as identity primary key, check_id text not null, snapshot jsonb not null, changed_by uuid references auth.users, changed_at timestamptz not null default now(), reason text);
create table public.audit_runs (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties on delete cascade, page_url text not null, status public.audit_status not null default 'queued', score int check(score between 0 and 100), coverage int check(coverage between 0 and 100), registry_snapshot jsonb not null, scoring_version text not null, started_at timestamptz, completed_at timestamptz, duration_ms int, error text, created_at timestamptz not null default now());
create table public.audit_results (id bigint generated always as identity primary key, audit_run_id uuid not null references public.audit_runs on delete cascade, check_id text not null, outcome public.check_outcome not null, evidence jsonb not null default '{}', duration_ms int not null default 0, logic_version text not null, configuration_version int not null, title_snapshot text not null, created_at timestamptz not null default now(), unique(audit_run_id,check_id));

create table public.analytics_events (id bigint generated always as identity primary key, property_id uuid not null references public.properties on delete cascade, event_type text not null check(event_type in ('pageview','click','outbound','scroll','active_time','form_success','web_vital')), path text not null, referrer_host text, source text, device text check(device is null or device in ('desktop','mobile','tablet')), country_code text check(country_code is null or country_code ~ '^[A-Z]{2}$'), name text, value numeric, metadata jsonb not null default '{}', occurred_at timestamptz not null, received_at timestamptz not null default now());
create table public.analytics_daily (property_id uuid not null references public.properties on delete cascade, day date not null, path text not null, event_type text not null, name text not null default '', device text not null default '', source text not null default '', country_code text not null default '', count bigint not null, value_sum numeric, primary key(property_id,day,path,event_type,name,device,source,country_code));
create table public.event_definitions (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties on delete cascade, name text not null, event_type text not null, description text, enabled boolean not null default true, created_at timestamptz not null default now(), unique(property_id,name));

create table public.report_templates (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, name text not null, sections jsonb not null default '["uptime","analytics","audit"]', branding jsonb not null default '{}', created_by uuid not null references auth.users, created_at timestamptz not null default now());
create table public.saved_reports (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties on delete cascade, template_id uuid references public.report_templates on delete set null, name text not null, period_start date not null, period_end date not null, data_snapshot jsonb not null, created_by uuid not null references auth.users, created_at timestamptz not null default now());
create table public.report_schedules (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties on delete cascade, template_id uuid references public.report_templates on delete set null, cadence text not null check(cadence in ('weekly','monthly')), recipients text[] not null, enabled boolean not null default true, next_run_at timestamptz not null, created_by uuid not null references auth.users, created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.accounts on delete cascade, user_id uuid references auth.users on delete cascade, title text not null, body text not null, severity text not null default 'info', read_at timestamptz, created_at timestamptz not null default now());
create table public.notification_deliveries (id uuid primary key default gen_random_uuid(), dedupe_key text not null unique, kind text not null, recipient text not null, payload jsonb not null default '{}', status text not null default 'claimed', provider_id text, error text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.activity_log (id bigint generated always as identity primary key, account_id uuid not null references public.accounts on delete cascade, actor_id uuid references auth.users on delete set null, action text not null, property_id uuid references public.properties on delete set null, metadata jsonb not null default '{}', created_at timestamptz not null default now());

create index properties_workspace_idx on public.properties(workspace_id);
create index uptime_due_idx on public.uptime_monitors(next_check_at) where enabled;
create index uptime_checks_monitor_time_idx on public.uptime_checks(monitor_id,checked_at desc);
create index incidents_property_time_idx on public.incidents(property_id,opened_at desc);
create index audit_runs_property_time_idx on public.audit_runs(property_id,created_at desc);
create index audit_results_run_outcome_idx on public.audit_results(audit_run_id,outcome);
create index analytics_events_property_time_idx on public.analytics_events(property_id,occurred_at desc);
create index notifications_user_time_idx on public.notifications(user_id,created_at desc);

create or replace function private.is_account_member(p_account uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.account_memberships m where m.account_id=p_account and m.user_id=(select auth.uid()))$$;
create or replace function private.is_workspace_member(p_workspace uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.workspace_memberships m where m.workspace_id=p_workspace and m.user_id=(select auth.uid()))$$;
create or replace function private.can_manage_workspace(p_workspace uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.workspace_memberships m where m.workspace_id=p_workspace and m.user_id=(select auth.uid()) and m.role in ('owner','member'))$$;
create or replace function private.can_access_property(p_property uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.properties p join public.workspace_memberships m on m.workspace_id=p.workspace_id where p.id=p_property and m.user_id=(select auth.uid()))$$;
revoke all on all functions in schema private from public,anon,authenticated;
grant usage on schema private to authenticated;
grant execute on function private.is_account_member(uuid),private.is_workspace_member(uuid),private.can_manage_workspace(uuid),private.can_access_property(uuid) to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,full_name) values(new.id,new.raw_user_meta_data->>'full_name') on conflict do nothing; return new; end$$;
revoke all on function public.handle_new_user() from public,anon,authenticated;
create trigger auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.complete_onboarding(p_account_name text,p_workspace_name text,p_property_name text default null,p_url text default null) returns jsonb language plpgsql security definer set search_path='' as $$declare uid uuid:=(select auth.uid()); aid uuid; wid uuid; pid uuid; host text;begin if uid is null then raise exception 'authentication required';end if;if exists(select 1 from public.account_memberships where user_id=uid) then raise exception 'onboarding already complete';end if;insert into public.accounts(name) values(p_account_name) returning id into aid;insert into public.account_memberships values(aid,uid,'owner',now());insert into public.workspaces(account_id,name) values(aid,p_workspace_name) returning id into wid;insert into public.workspace_memberships values(wid,uid,'owner',now());if nullif(trim(p_property_name),'') is not null and nullif(trim(p_url),'') is not null then host:=lower(regexp_replace(p_url,'^https?://([^/]+).*$','\1','i'));insert into public.properties(workspace_id,name,url,canonical_host,tracking_id) values(wid,p_property_name,p_url,host,'cl_'||replace(gen_random_uuid()::text,'-','')) returning id into pid;insert into public.uptime_monitors(property_id) values(pid);end if;insert into public.activity_log(account_id,actor_id,action,property_id) values(aid,uid,'onboarding.completed',pid);return jsonb_build_object('accountId',aid,'workspaceId',wid,'propertyId',pid);end$$;
revoke all on function public.complete_onboarding(text,text,text,text) from public,anon;
grant execute on function public.complete_onboarding(text,text,text,text) to authenticated;

create or replace function public.claim_notification(p_key text,p_kind text,p_recipient text,p_payload jsonb) returns boolean language plpgsql security definer set search_path='' as $$begin insert into public.notification_deliveries(dedupe_key,kind,recipient,payload) values(p_key,p_kind,p_recipient,p_payload) on conflict do nothing;return found;end$$;
revoke all on function public.claim_notification(text,text,text,jsonb) from public,anon,authenticated;

create or replace function public.analytics_summary(p_property_id uuid,p_from timestamptz,p_to timestamptz) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('pageviews',count(*) filter(where event_type='pageview'),'events',count(*),'pages',coalesce(jsonb_agg(distinct path) filter(where event_type='pageview'),'[]'::jsonb),'from',p_from,'to',p_to) from public.analytics_events where property_id=p_property_id and occurred_at>=p_from and occurred_at<p_to$$;
grant execute on function public.analytics_summary(uuid,timestamptz,timestamptz) to authenticated;
create or replace function public.aggregate_analytics_day(p_day date) returns void language sql security definer set search_path='' as $$insert into public.analytics_daily(property_id,day,path,event_type,name,device,source,country_code,count,value_sum) select property_id,p_day,path,event_type,coalesce(name,''),coalesce(device,''),coalesce(source,''),coalesce(country_code,''),count(*),sum(value) from public.analytics_events where occurred_at>=p_day::timestamptz and occurred_at<(p_day+1)::timestamptz group by 1,2,3,4,5,6,7,8 on conflict(property_id,day,path,event_type,name,device,source,country_code) do update set count=excluded.count,value_sum=excluded.value_sum$$;
revoke all on function public.aggregate_analytics_day(date) from public,anon,authenticated;

do $$declare t text;begin foreach t in array array['profiles','accounts','account_memberships','workspaces','workspace_memberships','properties','uptime_monitors','uptime_checks','maintenance_windows','incidents','alert_recipients','audit_check_definitions','audit_check_history','audit_runs','audit_results','analytics_events','analytics_daily','event_definitions','report_templates','saved_reports','report_schedules','notifications','notification_deliveries','activity_log'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
revoke all on all tables in schema public from anon,authenticated;
grant select,insert,update,delete on public.profiles,public.accounts,public.account_memberships,public.workspaces,public.workspace_memberships,public.properties,public.uptime_monitors,public.maintenance_windows,public.alert_recipients,public.event_definitions,public.report_templates,public.saved_reports,public.report_schedules,public.notifications to authenticated;
grant select on public.uptime_checks,public.incidents,public.audit_check_definitions,public.audit_runs,public.audit_results,public.analytics_events,public.analytics_daily,public.activity_log to authenticated;
grant insert on public.audit_runs to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create policy profile_self_select on public.profiles for select to authenticated using(id=(select auth.uid()));
create policy profile_self_update on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy account_member_select on public.accounts for select to authenticated using((select private.is_account_member(id)));
create policy account_membership_select on public.account_memberships for select to authenticated using((select private.is_account_member(account_id)));
create policy workspace_member_select on public.workspaces for select to authenticated using((select private.is_workspace_member(id)));
create policy workspace_membership_select on public.workspace_memberships for select to authenticated using((select private.is_workspace_member(workspace_id)));
create policy property_member_select on public.properties for select to authenticated using((select private.is_workspace_member(workspace_id)));
create policy property_manage_insert on public.properties for insert to authenticated with check((select private.can_manage_workspace(workspace_id)));
create policy property_manage_update on public.properties for update to authenticated using((select private.can_manage_workspace(workspace_id))) with check((select private.can_manage_workspace(workspace_id)));
create policy property_owner_delete on public.properties for delete to authenticated using(exists(select 1 from public.workspace_memberships m where m.workspace_id=properties.workspace_id and m.user_id=(select auth.uid()) and m.role='owner'));
create policy monitor_member_select on public.uptime_monitors for select to authenticated using((select private.can_access_property(property_id)));
create policy monitor_manage_update on public.uptime_monitors for update to authenticated using(exists(select 1 from public.properties p where p.id=property_id and (select private.can_manage_workspace(p.workspace_id)))) with check(exists(select 1 from public.properties p where p.id=property_id and (select private.can_manage_workspace(p.workspace_id))));
create policy child_property_select_checks on public.uptime_checks for select to authenticated using(exists(select 1 from public.uptime_monitors m where m.id=monitor_id and (select private.can_access_property(m.property_id))));
create policy child_property_select_incidents on public.incidents for select to authenticated using((select private.can_access_property(property_id)));
create policy maintenance_member_all on public.maintenance_windows for all to authenticated using(exists(select 1 from public.uptime_monitors m join public.properties p on p.id=m.property_id where m.id=monitor_id and (select private.can_manage_workspace(p.workspace_id)))) with check(exists(select 1 from public.uptime_monitors m join public.properties p on p.id=m.property_id where m.id=monitor_id and (select private.can_manage_workspace(p.workspace_id))));
create policy recipients_member_all on public.alert_recipients for all to authenticated using((select private.can_access_property(property_id))) with check((select private.can_access_property(property_id)));
create policy audit_registry_read on public.audit_check_definitions for select to authenticated using(lifecycle in ('active','deprecated','retired'));
create policy audit_run_select on public.audit_runs for select to authenticated using((select private.can_access_property(property_id)));
create policy audit_run_insert on public.audit_runs for insert to authenticated with check((select private.can_access_property(property_id)));
create policy audit_result_select on public.audit_results for select to authenticated using(exists(select 1 from public.audit_runs r where r.id=audit_run_id and (select private.can_access_property(r.property_id))));
create policy analytics_event_select on public.analytics_events for select to authenticated using((select private.can_access_property(property_id)));
create policy analytics_daily_select on public.analytics_daily for select to authenticated using((select private.can_access_property(property_id)));
create policy event_definition_all on public.event_definitions for all to authenticated using((select private.can_access_property(property_id))) with check((select private.can_access_property(property_id)));
create policy template_member_all on public.report_templates for all to authenticated using((select private.is_workspace_member(workspace_id))) with check((select private.can_manage_workspace(workspace_id)));
create policy saved_report_member_all on public.saved_reports for all to authenticated using((select private.can_access_property(property_id))) with check((select private.can_access_property(property_id)));
create policy schedule_member_all on public.report_schedules for all to authenticated using((select private.can_access_property(property_id))) with check((select private.can_access_property(property_id)));
create policy notifications_select on public.notifications for select to authenticated using(user_id=(select auth.uid()) or (user_id is null and (select private.is_account_member(account_id))));
create policy notifications_update on public.notifications for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy activity_select on public.activity_log for select to authenticated using((select private.is_account_member(account_id)));

-- Repeatable seed of registry metadata is performed by scripts/seed-audit-registry.mjs using the service key.
comment on table public.audit_check_definitions is 'Configuration and metadata only. Executable logic is allowlisted and version-controlled in src/worker.';
