-- Migration number retained because it was committed before the complete Stage 2
-- staff-security design was ready. It has never been applied to production.
--
-- The prototype email allowlist was intentionally removed before release: an
-- email address alone must never grant platform access, even temporarily. The
-- following 20261006012241 migration creates the definitive staff model and
-- binds access only to confirmed auth.users identities.
